services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - source_net
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sources/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  source-api:
    build: ./sources/api
    container_name: source-api
    ports:
      - "8000:8000"
    volumes:
      - ./sources/api:/app

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # minio API
      - "9001:9001" # minio UI
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data
    networks:
      - spark-net
    command: server /data --console-address ":9001"

  init-minio:
    image: quay.io/minio/mc
    depends_on:
      - minio
    volumes:
      - ./infra:/infra
    networks:
      - spark-net
    entrypoint: ["/bin/sh", "/infra/init.sh"]

  spark-master:
    build: ./spark-app
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master", "--port", "7077", "--webui-port", "8088"]
    environment:
      - PYTHONPATH=/opt/spark-app
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - S3_BRONZE_BUCKET=${S3_BRONZE_BUCKET}
      - S3_SILVER_BUCKET=${S3_SILVER_BUCKET}
      - S3_GOLD_BUCKET=${S3_GOLD_BUCKET}
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8088
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"
      - "8088:8088"
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-net

  spark-worker:
    build: ./spark-app
    container_name: spark-worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    environment:
      - PYTHONPATH=/opt/spark-app
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - S3_BRONZE_BUCKET=${S3_BRONZE_BUCKET}
      - S3_SILVER_BUCKET=${S3_SILVER_BUCKET}
      - S3_GOLD_BUCKET=${S3_GOLD_BUCKET}
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8089
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8089:8089"
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-net

networks:
  source_net:
  spark-net:

volumes:
  postgres_data:
  spark-logs: