services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - source_net
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sources/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  source-api:
    build: ./sources/api
    container_name: source-api
    ports:
      - "8000:8000"
    volumes:
      - ./sources/api:/app

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # minio API
      - "9001:9001" # minio UI
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  init-minio:
    image: quay.io/minio/mc
    depends_on:
      - minio
    volumes:
      - ./infra:/infra
    entrypoint: ["/bin/sh", "/infra/init.sh"]

  spark:
    image: spark:3.5.8-scala2.12-java11-python3-ubuntu
    container_name: spark-local
    ports:
      - "4040:4040"  #Spark UI
    working_dir: /opt/spark/jobs
    volumes:
      - ./spark:/opt/spark/project
    command: ["sleep", "infinity"]

networks:
  source_net:

volumes:
  postgres_data: